### ISSUE TITLE
Should ImageFragment check position?

### ISSUE THREAD

**Issue by natario1** [google/android-transition-examples#2]
Referring to this:

https://github.com/google/android-transition-examples/blob/6910b1ff673c1abdeff9515d97c41b34f7ee2efc/GridToPager/app/src/main/java/com/google/samples/gridtopager/fragment/ImageFragment.java#L74

I think you should check for position to before calling `startPostponedEnterTransition`, right?
You are assuming that the first `ImageFragment` image to be loaded is the requested one, but that's not so obvious e.g. with network pictures. Correct me if I'm wrong.

**Comment by codingjeremy** [comment]
This issue has been migrated to the new animations repo: [github.com/android/animation](https://github.com/android/animation).
