### ISSUE TITLE
Square images in grid view

### ISSUE THREAD

**Issue by sbakhtiarov** [google/android-transition-examples#3]
Could you please suggest the way to handle image transformation from a square view (with centerCrop applied) in RecyclerView to a full screen (fitCenter) in the image details fragment?
Once I add the cropping the animations are broken. The image is not scaled correctly and size jumps when it is animated back from full screen.

**Comment by muthuraj57** [comment]
Any update? Changing _fitCenter_ to _centerCrop_ in ImageView of **image_card** layout produces broken animation.

**Comment by frfmmdreza** [comment]
any update? this is my problem too.

**Comment by guillaume-tgl** [comment]
I'm interested in the answer too :)

**Comment by codingjeremy** [comment]
This issue has been migrated to the new animations repo: [github.com/android/animation](https://github.com/android/animation).
