### ISSUE TITLE
NPE because of android:duration

### ISSUE THREAD

**Issue by yallam08** [google/android-transition-examples#8]
The `android:duration` attribute in _image_shared_element_transition.xml_ file causes a NPE

But when it's removed and the duration is set programmatically, it works fine:
`Transition transition = TransitionInflater.from(getContext()).inflateTransition(R.transition.image_shared_element_transition);
transition.setDuration(375);`

**Comment by codingjeremy** [comment]
This issue has been migrated to the new animations repo: [github.com/android/animation](https://github.com/android/animation).
